version: '3.1'

services:

  ghost:
    image: ghost:4-alpine
    restart: always
    # ports:
    #   - 8090:2368
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`auto-gpt.tech`)"
      - "traefik.http.routers.ghost.entrypoints=websecure"
      - "traefik.http.routers.ghost.tls.certresolver=myresolver"
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: https://auto-gpt.tech
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    networks:
      - auto-gpt.tech
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    
volumes:
  ghost-db-data:
networks:
  auto-gpt.tech:
    external: true